/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View,TouchableHighlight,requireNativeComponent } from 'react-native';
import Palmmob3AdLibs from 'react-native-palmmob3-ad-libs';

const SplashView = requireNativeComponent("GDTSplashView");

export default class App extends Component {
  state = {
    status: 'starting',
    message: '--',
    inited:false
  };

  async componentDidMount() {
    await Palmmob3AdLibs.initGDT('1111964523');
    await Palmmob3AdLibs.setGDTChannel(10);
    this.setState({
      inited:true
    });
  }

  onAdError(evt) {
    console.log(evt.nativeEvent);
  }

  onAdClick(evt) {
    console.log(evt.nativeEvent);
  }

  onAdClose(evt) {
    console.log(evt.nativeEvent);
    this.setState({
      inited:false
    });
  }

  onAdLoad(evt) {
    console.log(evt.nativeEvent);
  }

  onAdShow(evt) {
    console.log(evt.nativeEvent);
  }

  render() {
    if(this.state.inited){
      return ( 
        <View style={styles.container}>
          <SplashView style={styles.splash} PosId='3032809667717528' 
              onAdError={this.onAdError.bind(this)}  onAdClick={this.onAdClick.bind(this)} 
              onAdClose={this.onAdClose.bind(this)}  onAdLoad={this.onAdLoad.bind(this)} 
              onAdShow={this.onAdShow.bind(this)}  />
        </View>
      );
    }
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆Palmmob3AdLibs example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>        
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#00FF00',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  splash: {    
    // flex:1,
    width:"100%",
    height:"100%"
  }
});
